#Workflow name
name: Test Pipeline
on:
  workflow_dispatch:
  push:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      # Maven package cache to "improve" speed
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Tests
        run: mvn test
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cocletima-tests:latest

  newman:
    needs: [tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install -g newman
      - run: newman run 'newman_tests.json'

    container: node:10.19-jessie

    services:
      api-adder:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/cocletima-tests:latest
        ports:
          - 8080:8080
