#Workflow name
name: Test Pipeline
on:
  workflow_dispatch:
  push:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      # Maven package cache to "improve" speed
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Tests
        run: mvn test
      - uses: actions/checkout@master
      - name: Run SrpingBoot Application and test it with newman (postman)
        uses: actions/tp-bootful-tests-api-cocletima@v1
        run: | 
          docker run -v $(pwd)/src/test:/etc/newman -t postman/newman:latest run "resources/newman_tests.json" --reporters="cli"
          docker kill $(docker ps -q)
